import { IData } from '@/types/data.types'

export function useData() {
  const mockData: IData = {
    benchmark: {
      participation: 97,
      eNPS: 97,
      overall_engagement: 8.1,
      recognition: 8.1,
      feedback: 8.1,
      relationship_with_peers: 8.1,
      relationship_with_manager: 8.1,
      satisfaction: 8.1,
      alignment: 8.1,
      happiness: 8.1,
      wellness: 8.1,
      personal_growth: 8.1,
      ambassadorship: 8.1,
    },
    teams: [
      {
        name: 'All Teams',
        participation: 97,
        eNPS: 97,
        overall_engagement: 6.2,
        recognition: 4.9,
        feedback: 6.2,
        relationship_with_peers: 6.2,
        relationship_with_manager: 6.2,
        satisfaction: 6.2,
        alignment: 6.2,
        happiness: 6.2,
        wellness: 6.2,
        personal_growth: 6.2,
        ambassadorship: 6.2,
      },
      {
        name: 'Team Brazil',
        participation: 97,
        eNPS: 97,
        overall_engagement: 6.2,
        recognition: 6.2,
        feedback: 4.5,
        relationship_with_peers: 8.4,
        relationship_with_manager: 6.2,
        satisfaction: 6.2,
        alignment: 6.2,
        happiness: 6.2,
        wellness: 6.2,
        personal_growth: 6.2,
        ambassadorship: 6.2,
      },
      {
        name: 'Team US',
        participation: 97,
        eNPS: 97,
        overall_engagement: 6.1,
        recognition: 3.0,
        feedback: 6.1,
        relationship_with_peers: 6.1,
        relationship_with_manager: 6.1,
        satisfaction: 3.0,
        alignment: 6.1,
        happiness: 6.1,
        wellness: 6.1,
        personal_growth: 6.1,
        ambassadorship: 6.1,
      },
    ],
  }

  const headers: string[] = [
    'Participation (%)',
    'eNPS',
    'Overall Engagement',
    'Recognition',
    'Feedback',
    'Relationship with Peers',
    'Relationship with Manager',
    'Satisfaction',
    'Alignment',
    'Happiness',
    'Wellness',
    'Personal Growth',
    'Ambassadorship',
  ]

  return { mockData, headers }
}
