/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AnalysisComparisonLazyImport = createFileRoute('/Analysis/Comparison')()

// Create/Update Routes

const AnalysisComparisonLazyRoute = AnalysisComparisonLazyImport.update({
  path: '/Analysis/Comparison',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/Analysis/Comparison.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Analysis/Comparison': {
      id: '/Analysis/Comparison'
      path: '/Analysis/Comparison'
      fullPath: '/Analysis/Comparison'
      preLoaderRoute: typeof AnalysisComparisonLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ AnalysisComparisonLazyRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/Analysis/Comparison"
      ]
    },
    "/Analysis/Comparison": {
      "filePath": "Analysis/Comparison.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
